using System.Globalization;
using System.Resources;

namespace Fct.App.Lang;

// Typed accessors over Resources.resx and its future Resources.<culture>.resx satellites.
// Hand-written rather than generated by Visual Studio's ResXFileCodeGenerator, so `dotnet build`
// alone is sufficient — adding a translation only ever means adding a new Resources.<culture>.resx
// with matching keys; adding a new UI string means adding one property here plus the resx entry.
public static class Resources
{
    private static readonly ResourceManager Manager = new("Fct.App.Lang.Resources", typeof(Resources).Assembly);

    // Set once at startup by LocalizationStartup; x:Static references re-resolve against this only
    // if the view is (re)created afterward — see the restart-on-change note there.
    public static CultureInfo? Culture { get; set; }

    private static string Get(string name) => Manager.GetString(name, Culture) ?? name;

    // ---- General labels ----
    public static string Label_App => Get(nameof(Label_App));
    public static string Label_Game => Get(nameof(Label_Game));
    public static string Label_ClassicEngine => Get(nameof(Label_ClassicEngine));
    public static string Label_ClassicChip => Get(nameof(Label_ClassicChip));
    public static string Label_ModernChip => Get(nameof(Label_ModernChip));
    public static string Label_IssuesChip => Get(nameof(Label_IssuesChip));
    public static string Label_ClassicRuntime => Get(nameof(Label_ClassicRuntime));
    public static string Label_ModernRuntime => Get(nameof(Label_ModernRuntime));
    public static string Label_Identity => Get(nameof(Label_Identity));
    public static string Label_Version => Get(nameof(Label_Version));
    public static string Label_Contract => Get(nameof(Label_Contract));
    public static string Label_Duration => Get(nameof(Label_Duration));
    public static string Label_RaidDps => Get(nameof(Label_RaidDps));
    public static string Label_JobFormat => Get(nameof(Label_JobFormat));
    public static string Placeholder_Dash => Get(nameof(Placeholder_Dash));

    // ---- Navigation (also reused as page eyebrow/title) ----
    public static string Nav_Overview => Get(nameof(Nav_Overview));
    public static string Nav_Plugins => Get(nameof(Nav_Plugins));
    public static string Nav_Encounters => Get(nameof(Nav_Encounters));
    public static string Nav_Settings => Get(nameof(Nav_Settings));

    // ---- All-caps section eyebrows ----
    public static string Eyebrow_Host => Get(nameof(Eyebrow_Host));
    public static string Eyebrow_Plugins => Get(nameof(Eyebrow_Plugins));
    public static string Eyebrow_Classic => Get(nameof(Eyebrow_Classic));
    public static string Eyebrow_Modern => Get(nameof(Eyebrow_Modern));

    // ---- Actions / buttons ----
    public static string Action_RestartClassicEngine => Get(nameof(Action_RestartClassicEngine));
    public static string Action_ManagePlugins => Get(nameof(Action_ManagePlugins));
    public static string Action_OpenNotifications => Get(nameof(Action_OpenNotifications));
    public static string Action_AddPlugin => Get(nameof(Action_AddPlugin));
    public static string Action_ConfigurePlugins => Get(nameof(Action_ConfigurePlugins));
    public static string Action_ViewEncounters => Get(nameof(Action_ViewEncounters));
    public static string Action_Restart => Get(nameof(Action_Restart));
    public static string Action_Clear => Get(nameof(Action_Clear));
    public static string Action_OpenLogsFolder => Get(nameof(Action_OpenLogsFolder));

    // ---- Accessibility names ----
    public static string A11y_Notifications => Get(nameof(A11y_Notifications));
    public static string A11y_Minimize => Get(nameof(A11y_Minimize));
    public static string A11y_MaximizeRestore => Get(nameof(A11y_MaximizeRestore));
    public static string A11y_Close => Get(nameof(A11y_Close));
    public static string A11y_CloseNotifications => Get(nameof(A11y_CloseNotifications));
    public static string A11y_DismissNotification => Get(nameof(A11y_DismissNotification));
    public static string A11y_ClassicPluginsList => Get(nameof(A11y_ClassicPluginsList));
    public static string A11y_ModernPluginsList => Get(nameof(A11y_ModernPluginsList));

    // ---- Status bar / connection state ----
    public static string Status_AppRunning => Get(nameof(Status_AppRunning));
    public static string Status_GameFormat => Get(nameof(Status_GameFormat));
    public static string Status_Live => Get(nameof(Status_Live));
    public static string Status_LastFight => Get(nameof(Status_LastFight));
    public static string Status_Starting => Get(nameof(Status_Starting));
    public static string Status_Running => Get(nameof(Status_Running));
    public static string Status_Loaded => Get(nameof(Status_Loaded));
    public static string Status_NotLoaded => Get(nameof(Status_NotLoaded));
    public static string Status_Unavailable => Get(nameof(Status_Unavailable));
    public static string Status_Error => Get(nameof(Status_Error));
    public static string Status_NotConnected => Get(nameof(Status_NotConnected));
    public static string Status_WaitingForCombat => Get(nameof(Status_WaitingForCombat));
    public static string Status_Stopped => Get(nameof(Status_Stopped));
    public static string Status_NotStarted => Get(nameof(Status_NotStarted));
    public static string Status_EngineStoppedSummary => Get(nameof(Status_EngineStoppedSummary));
    public static string Status_EngineNotStartedSummary => Get(nameof(Status_EngineNotStartedSummary));
    public static string Status_StartingEngineSummary => Get(nameof(Status_StartingEngineSummary));
    public static string Status_EngineRunningSummary_One => Get(nameof(Status_EngineRunningSummary_One));
    public static string Status_EngineRunningSummary_Many => Get(nameof(Status_EngineRunningSummary_Many));

    // ---- Notifications (toasts / centre) ----
    public static string NotificationCenter_Title => Get(nameof(NotificationCenter_Title));
    public static string NotificationCenter_Subtitle => Get(nameof(NotificationCenter_Subtitle));
    public static string NotificationCenter_EmptyTitle => Get(nameof(NotificationCenter_EmptyTitle));
    public static string NotificationCenter_EmptyBody => Get(nameof(NotificationCenter_EmptyBody));
    public static string Notify_Source_ClassicEngine => Get(nameof(Notify_Source_ClassicEngine));
    public static string Notify_Source_ClassicPlugin => Get(nameof(Notify_Source_ClassicPlugin));
    public static string Notify_Source_Plugins => Get(nameof(Notify_Source_Plugins));
    public static string Notify_EngineRunningTitle => Get(nameof(Notify_EngineRunningTitle));
    public static string Notify_EngineReady_One => Get(nameof(Notify_EngineReady_One));
    public static string Notify_EngineReady_Many => Get(nameof(Notify_EngineReady_Many));
    public static string Notify_EngineStartFailedTitle => Get(nameof(Notify_EngineStartFailedTitle));
    public static string Notify_EngineStoppedTitle => Get(nameof(Notify_EngineStoppedTitle));
    public static string Notify_EngineStoppedBody => Get(nameof(Notify_EngineStoppedBody));
    public static string Notify_PluginReportedErrorTitle => Get(nameof(Notify_PluginReportedErrorTitle));
    public static string Notify_PluginLoadFailedTitle => Get(nameof(Notify_PluginLoadFailedTitle));
    public static string Notify_EngineErrorTitle => Get(nameof(Notify_EngineErrorTitle));
    public static string Notify_EngineWarningTitle => Get(nameof(Notify_EngineWarningTitle));
    public static string Notify_NotAPluginFolderTitle => Get(nameof(Notify_NotAPluginFolderTitle));
    public static string Notify_NotAPluginFolderBody => Get(nameof(Notify_NotAPluginFolderBody));
    public static string Notify_PluginInstalledTitleFormat => Get(nameof(Notify_PluginInstalledTitleFormat));
    public static string Notify_PluginInstalledBody => Get(nameof(Notify_PluginInstalledBody));
    public static string Notify_PluginInstallFailedTitle => Get(nameof(Notify_PluginInstallFailedTitle));
    public static string Dialog_AddPluginFolderTitle => Get(nameof(Dialog_AddPluginFolderTitle));

    // ---- Overview page ----
    public static string Overview_Subtitle => Get(nameof(Overview_Subtitle));
    public static string Overview_ConnectionTitle => Get(nameof(Overview_ConnectionTitle));
    public static string Overview_RecentActivityTitle => Get(nameof(Overview_RecentActivityTitle));
    public static string Overview_EmptyActivityTitle => Get(nameof(Overview_EmptyActivityTitle));
    public static string Overview_EmptyActivityBody => Get(nameof(Overview_EmptyActivityBody));
    public static string Overview_LoadedSummaryFormat => Get(nameof(Overview_LoadedSummaryFormat));

    // ---- Plugins page ----
    public static string Plugins_Subtitle => Get(nameof(Plugins_Subtitle));
    public static string Plugins_EngineDownTitle => Get(nameof(Plugins_EngineDownTitle));
    public static string Plugins_NoClassicLoaded => Get(nameof(Plugins_NoClassicLoaded));
    public static string Plugins_NoModernInstalled => Get(nameof(Plugins_NoModernInstalled));
    public static string Plugins_SelectPluginTitle => Get(nameof(Plugins_SelectPluginTitle));
    public static string Plugins_SelectPluginBody => Get(nameof(Plugins_SelectPluginBody));
    public static string Plugins_ConfigLoadingBody => Get(nameof(Plugins_ConfigLoadingBody));
    public static string Plugins_ModernConfigNote => Get(nameof(Plugins_ModernConfigNote));
    public static string Plugins_ConfiguredInPlugin => Get(nameof(Plugins_ConfiguredInPlugin));
    public static string Plugins_NoConfigToShow => Get(nameof(Plugins_NoConfigToShow));
    public static string Plugins_ConfigUnavailable => Get(nameof(Plugins_ConfigUnavailable));
    public static string Plugins_ModernNoEmbedBody => Get(nameof(Plugins_ModernNoEmbedBody));
    public static string Plugins_ClassicNoWindowBody => Get(nameof(Plugins_ClassicNoWindowBody));
    public static string Plugins_EngineDownBody => Get(nameof(Plugins_EngineDownBody));
    public static string Plugins_ModernPluginRole => Get(nameof(Plugins_ModernPluginRole));
    public static string Plugins_ModernPluginDescription => Get(nameof(Plugins_ModernPluginDescription));

    // ---- Encounters page ----
    public static string Encounters_Subtitle => Get(nameof(Encounters_Subtitle));
    public static string Encounters_WaitingTitle => Get(nameof(Encounters_WaitingTitle));
    public static string Encounters_WaitingBody => Get(nameof(Encounters_WaitingBody));
    public static string Encounters_DefaultTitle => Get(nameof(Encounters_DefaultTitle));
    public static string Column_Rank => Get(nameof(Column_Rank));
    public static string Column_Combatant => Get(nameof(Column_Combatant));
    public static string Column_Dps => Get(nameof(Column_Dps));
    public static string Column_Damage => Get(nameof(Column_Damage));
    public static string Column_Hps => Get(nameof(Column_Hps));
    public static string Column_Deaths => Get(nameof(Column_Deaths));

    // ---- Settings page ----
    public static string Settings_Subtitle => Get(nameof(Settings_Subtitle));
    public static string Settings_StartupTitle => Get(nameof(Settings_StartupTitle));
    public static string Settings_AutoStartLabel => Get(nameof(Settings_AutoStartLabel));
    public static string Settings_AutoStartDescription => Get(nameof(Settings_AutoStartDescription));
    public static string Settings_AppearanceTitle => Get(nameof(Settings_AppearanceTitle));
    public static string Settings_ThemeLabel => Get(nameof(Settings_ThemeLabel));
    public static string Settings_ThemeDescription => Get(nameof(Settings_ThemeDescription));
    public static string Settings_DiagnosticsTitle => Get(nameof(Settings_DiagnosticsTitle));
    public static string Settings_LogsLabel => Get(nameof(Settings_LogsLabel));
    public static string Settings_AboutTitle => Get(nameof(Settings_AboutTitle));
    public static string Settings_AboutDescription => Get(nameof(Settings_AboutDescription));

    // ---- Legacy plugin catalog ----
    public static string Catalog_Ffxiv_Role => Get(nameof(Catalog_Ffxiv_Role));
    public static string Catalog_Ffxiv_Description => Get(nameof(Catalog_Ffxiv_Description));
    public static string Catalog_Overlay_Role => Get(nameof(Catalog_Overlay_Role));
    public static string Catalog_Overlay_Description => Get(nameof(Catalog_Overlay_Description));
    public static string Catalog_Triggernometry_Role => Get(nameof(Catalog_Triggernometry_Role));
    public static string Catalog_Triggernometry_Description => Get(nameof(Catalog_Triggernometry_Description));
    public static string Catalog_Discord_Role => Get(nameof(Catalog_Discord_Role));
    public static string Catalog_Discord_Description => Get(nameof(Catalog_Discord_Description));
    public static string Catalog_Hojoring_Role => Get(nameof(Catalog_Hojoring_Role));
    public static string Catalog_Hojoring_Description => Get(nameof(Catalog_Hojoring_Description));
    public static string Catalog_Probe_Role => Get(nameof(Catalog_Probe_Role));
    public static string Catalog_Probe_Description => Get(nameof(Catalog_Probe_Description));
    public static string Catalog_Fallback_Role => Get(nameof(Catalog_Fallback_Role));
    public static string Catalog_Fallback_Description => Get(nameof(Catalog_Fallback_Description));
}
